### ISSUE TITLE
Add support for NOT IN operator

### ISSUE THREAD

**Issue by ggeremy** [raymanrt/orientqb#12]
Is it possible to add theses new operators ?
NOT_IN("%s NOT IN (%s)")
NOT_IN_WITHOUT_PARENTHESIS("%s NOT IN %s")

to create query like this:
select from T where attr1="toto" AND attr2 NOT IN [val1'', 'val2']
instead of
select from T where attr1="toto" AND NOT (attr2 IN [val1'', 'val2'])

Thank you
Geremy

**Comment by raymanrt** [comment]
I'm not sure NOT_IN_WITHOUT_PARENTHESIS is required.
NOT_IN operator can be unique as IN operator is.

If you don't think so can you please give me an example?

**Comment by raymanrt** [comment]
Please take a look at the current implementation and tell me what you think about it: OperatorTest.notInTest
