### ISSUE TITLE
Should support standalone out projections

### ISSUE THREAD

**Issue by karolmie1** [raymanrt/orientqb#13]
I see how with the current api i can archive .out('hasPermission') <== notice the dot, but how to do something like out('hasPermission').  <== no dot here

Implementation would probably require new class OutProjection, or something like that.

**Comment by raymanrt** [comment]
Hi, if I understood you mean a Projection Function such this:
`	@Test
	public void outQueryTest() {
		Query q = new Query()
				.select(ProjectionFunction.out("hasPermission"))
				.from("V");

		assertEquals("SELECT out('hasPermission') FROM V", q.toString());
	}
`

I've also added a unit test in QueryTest.java.

If this was your need we can close the issue, otherwise explain it better.
