### ISSUE TITLE
Missing method to copy query / idempotent queries

### ISSUE THREAD

**Issue by karolmie1** [raymanrt/orientqb#15]
right now you cannot reuse parts of queries.
It would be nice if the queries were idempotent (slow down would be negligible IMHO)

At least clone, or copy method should be provided, to receive new instance of copy to reuse.

**Comment by raymanrt** [comment]
That's an interesting idea I didn't consider.

Could you please give some example of idempotent queries?

**Comment by karolmie1** [comment]
Please take a look at: [my repo](https://bitbucket.org/kmierzej/fragaria-server/src/f718f39466f3eed80e61faecebbe5831fa938555/src/main/kotlin/pl/eightandcounting/fragaria/repository/query/PagedResourceQueryBuilder.kt?at=master&fileviewer=file-view-default)

I am preparing a base query, and then using it in other, more usefull queries: 
`
private fun prepareBaseQuery(): Query = Query().select(key).select(*projections).from(clazz)

private fun prepareAfterQuery() = prepareBaseQuery().where(KEY.gt(KEY_PARAM)).orderBy(key).limit(LIMIT_PARAM).toString()

private fun prepareFromQuery() = prepareBaseQuery().where(KEY.ge(KEY_PARAM)).orderBy(key).limit(LIMIT_PARAM).toString()
`

It would be just nice to have, because as you can see I've managed to get around it.

**Comment by raymanrt** [comment]
I think this feature would require a clone method for each Class and this could add some complexity to the source code.

You can always have a method or a function to generate a base query so I'm not really convinced on the implementation.

**Comment by karolmie1** [comment]
Yeah I gues it's not necesary, or even particulary usefull. I'll just close it.
