### ISSUE TITLE
select * should not override other selects.

### ISSUE THREAD

**Issue by karolmie1** [raymanrt/orientqb#16]
right now if I use select all it overrides all other selects, for example out(likes).type, so I cannot perform this query: 
`SELECT *, out(likes).type from User WHERE login= ?`

**Comment by raymanrt** [comment]
fixed in lastest commit, take a look at this unit test:
```
@Test
    public void allAndFieldQueryTest() {
        Query q = new Query();
        q.select(Projection.ALL);
        q.select("field");
        q.from("Class");
        assertEquals("SELECT *, field FROM Class", q.toString());
    }
```
