### ISSUE TITLE
Common interface for delete and query

### ISSUE THREAD

**Issue by karolmie1** [raymanrt/orientqb#18]
Right now Query and Delete extend AbstractQuery class. It would be nice if they implemented common interface, so I would be able to reuse some helper functions on both of them.

**Comment by raymanrt** [comment]
Why can't your helper function receive an AbstractQuery?

**Comment by karolmie1** [comment]
Because it's a class with protected methods. I would need to hack around java around to call them, and also I'm not sure if I would call direct or polimorphic method.

**Comment by raymanrt** [comment]
Which methods should the interface expose in your opinion?
