### ISSUE TITLE
Delete queries don't work

### ISSUE THREAD

**Issue by karolmie1** [raymanrt/orientqb#19]
At least in newer orientdb versions simple query like: 
`DELETE Profile `

Does not work. It has to be: 
`DELETE VERTEX Profile`

**Comment by raymanrt** [comment]
What do you think about this solution?

**Comment by karolmie1** [comment]
I hacked around passing "VERTEX Profile", to from() function. 

I know what you are trying to say though :) I'll try to find the strength inside me to propose pull request.
