### ISSUE TITLE
Add support for IS NULL and IS NOT NULL

### ISSUE THREAD

**Issue by wouterv** [raymanrt/orientqb#3]
for example:

select from Foo where bar is null
and
select from Foo where bar is not null

**Comment by raymanrt** [comment]
I forgot them, what do you think?

Riccardo

**Comment by wouterv** [comment]
Looks good to me!

**Comment by wouterv** [comment]
Great, thanks. Will there be a new release with this change?

**Comment by raymanrt** [comment]
Why not, do you think there should be something else for a 1.3 release?

**Comment by wouterv** [comment]
I'm missing UPDATE and TRAVERSE, but I guess that's a lot more work.

I scanned our code and I'm not seeing anything else that is missing. 

Your library is brilliant, more people should use it ;-)

**Comment by raymanrt** [comment]
Ok, you flattered me: I don't know when I'll be available to implement also UPDATE and TRAVERSE but I could release 1.3 in a few days.

Of course I also hope that others find usefull orienqb :)

**Comment by raymanrt** [comment]
I have also questions for you:
* how do you use orientqb?
* have you tested with the new query parser of orient 2.1?

**Comment by wouterv** [comment]
1 Not sure how to answer this. We just use it for queries and we have our own dao structure that have some common query methods into which orientqb plays a vital role.
2 No, we are on 2.0.x and will probably not upgrade to 2.1.x as there aren't really interesting changes for us, 2.2.x is more promising (sequences, lazy loading objects support). If we do upgrade we'll wait until at least a couple of bugfix releases are done.

As for getting more users to use it, I would suggest plugging it on the mailing list everytime you get a release, or asking Luca to add a link on their libraries page: http://orientdb.com/docs/last/Plugins.html
In fact, since a few weeks they accept pull requests for their documentation.
https://github.com/orientechnologies/orientdb-docs

**Comment by raymanrt** [comment]
Thanks for your good suggestions!
The 0.1.3 should be releasead on sonatype, let me know if you see something wrong ;)

**Comment by wouterv** [comment]
Already got it and building in our code!
